AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Notification Service (WA, SMS, Email)

Parameters:
  Env:
    Type: String
    Default: local
  DynamoEndpoint:
    Type: String
    Default: http://host.docker.internal:8000
  DynamoDBTable:
    Type: String
    Default: NotificationService
  TwilioAccountSid:
    Type: String
    Default: ""
    Description: "Twilio Account SID"
  TwilioAuthToken:
    Type: String
    Default: ""
    NoEcho: true
    Description: "Twilio Auth Token"
  TwilioWhatsAppNumber:
    Type: String
    Default: ""
    Description: "Twilio WhatsApp Number (e.g., +14155238886)"

Globals:
  Function:
    Timeout: 10
    Runtime: provided.al2023
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        ENV: !Ref Env
        DYNAMO_ENDPOINT: !Ref DynamoEndpoint
        TABLE_NAME: !Ref DynamoDBTable
        TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
        TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
        TWILIO_WHATSAPP_NUMBER: !Ref TwilioWhatsAppNumber

Resources:
  #######################################
  # API GATEWAY
  #######################################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  #######################################
  # LAMBDA: Register Business
  #######################################
  RegisterBusinessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        RegisterBusinessApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/business/register
            Method: POST
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        Target: RegisterBusinessFunction

  #######################################
  # LAMBDA: Regenerate API Key
  #######################################
  RegenerateAPIKeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        RegenerateKeyApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/account/regenerate-key
            Method: POST
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        Target: RegenerateAPIKeyFunction

  #######################################
  # LAMBDA: Account Info
  #######################################
  AccountInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        AccountInfoApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/account/info
            Method: GET
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        Target: AccountInfoFunction

  #######################################
  # LAMBDA: Plan Usage
  #######################################
  PlanUsageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        PlanUsageApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/plan/usage
            Method: GET
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        Target: PlanUsageFunction

  #######################################
  # LAMBDA: Send WhatsApp Notification
  #######################################
  SendWhatsAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        SendWhatsAppApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/notifications/whatsapp
            Method: POST
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        Target: SendWhatsAppFunction

  #######################################
  # LAMBDA: Send SMS Notification
  #######################################
  SendSMSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        SendSMSApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/notifications/sms
            Method: POST
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        Target: SendSMSFunction

  #######################################
  # LAMBDA: Send Email Notification
  #######################################
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        SendEmailApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /v1/notifications/email
            Method: POST
    Metadata:
      BuildMethod: makefile
      BuildProperties:
        Target: SendEmailFunction

  # #######################################
  # # LAMBDA: Get Templates (OLD - COMMENTED)
  # #######################################
  # # SendNotificationFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: api/send_notification
  #     CodeUri: api/
  #     Policies:
  #       - DynamoDBCrudPolicy:
  #           TableName: NotificationService
  #     Events:
  #       SendNotificationApi:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ApiGateway
  #           Path: /send-notification
  #           Method: POST

  # #######################################
  # # LAMBDA: Get Templates
  # #######################################
  # GetTemplatesFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: api/get_templates
  #     CodeUri: api/
  #     Policies:
  #       - DynamoDBReadPolicy:
  #           TableName: NotificationService
  #     Events:
  #       GetTemplatesApi:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ApiGateway
  #           Path: /templates
  #           Method: GET

  # #######################################
  # # LAMBDA: Get Plans
  # #######################################
  # GetPlansFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: api/get_plans
  #     CodeUri: api/
  #     Policies:
  #       - DynamoDBReadPolicy:
  #           TableName: NotificationService
  #     Events:
  #       GetPlansApi:
  #         Type: Api
  #         Properties:
  #           RestApiId: !Ref ApiGateway
  #           Path: /plans
  #           Method: GET

# Outputs:
#   ApiUrl:
#     Description: "API base URL"
#     Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
